* Startup
** X
Start up a background (note, requires feh is installed)
#+BEGIN_SRC sh
feh --bg-scale ~/dotfiles/background.jpg
#+END_SRC

** xmonad
*** Install
Install through cabal for an update to dat version, with up-todate extensions. It must then be manually registered with gdm (gnome display manager / login manager) or any such alternative.
*** Screenshot
Install scrot to to allow for screenshots.


** urxvt
rxvt-unicode is a terminal emulator.
*** colors
Default debian package is 88-color version, be sure to select 256-color version from repo.

Colors for the 'ls' command can be configured with. Which is in my .zshrc file.
#+BEGIN_SRC sh
eval "$(dircolors -b ~/.dotfiles/LS_COLORS)"
#+END_SRC

More usefully, colors, such as blue in the example below, can be globally replaced in urxvt with
#+BEGIN_SRC 
URxvt*color4: #009B7B
URxvt*color12: #009B7B
#+END_SRC
*** urxvt-perls
https://github.com/muennich/urxvt-perls
Collection of perl script to allow things like copy/paste with keyboard to happen.

** tmux
Terminal multiplexer.

Can be extended with tmuxinator.
* Useful programs
** z
Shell script allows you to jump to recently/oftenly used directories by passing it a in-order sequence of words appearing in the targets' full path.
https://github.com/rupa/z
** htop
Thoroughly superior alternative to top. Colored, nice-lookin', etc.
