#!/bin/sh
# Used for general, on-startup actions.

# Computer-specific settings
source ~/.ss

# emacs setup
export ALTERNATE_EDITOR=emacs EDITOR=emacsclient VISUAL=emacsclient

# Add cabal binaries
export PATH=/home/aapollon/.cabal/bin/:$PATH
export PATH=/home/apple/.cabal/bin/:$PATH

